### ISSUE TITLE
[Docs] Add all site argument and example to Command section

### ISSUE THREAD

**Issue by napcok** [majick777/wpx#10]
Feature request:
It is possible to add keyword "all" - meaning all available sites to run command on all sities?
Like for example
`wpx listplugins all`
instead of
`wpx listplugins site1,site2,site3,site4`

**Comment by majick777** [comment]
@Napcok Apologies for the late reply, seems like I forgot to turn on notifications for this repository.

Actually what you describe is exactly how that works already, the `all` is accepted as a valid argument and runs the command on each site one by one in the order they are in the config file.

So I guess this could be added to the command documentation. Thanks for the input!
