### ISSUE TITLE
[Docs] Add CentOS Fix procedure to Installation section

### ISSUE THREAD

**Issue by napcok** [majick777/wpx#8]
Very interesting project, thanks for sharing :)
For now, I'm using my own scripts, but I'm also testing wpx - it's more mature and promising.
Question:
What distribution are you testing wpx on?
I have problems with sudo on CentOS - can't see wp (wp-cli), I will test it more. It works fine on Ubuntu.

I will continue testing wpx. And maybe I'll post a bugreport or pull request soon.

**Comment by napcok** [comment]
I have fix for CentOS.
Put /usr/local/bin/ to /etc/sudoers
`Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin/`

**Comment by majick777** [comment]
@napcok Thanks for your fix for Centos! WPX is currently developed on Ubuntu.

Something I could add to the documentation, can you add a little more information on the process of where and how to add this for CentOS users that are not familiar with it?
